spring.application.name=tawerna-mtb-api

# Database connection configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/tawernamtb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate DDL-Auto configuration (Automatically updates DB schema based on Kotlin entity classes)
spring.jpa.hibernate.ddl-auto=update

# Show raw SQL queries executed by Spring Data JPA in the terminal output
spring.jpa.show-sql=true

# Force SQL initialization script to run always, even for external databases like PostgreSQL
spring.sql.init.mode=always

# Tell Hibernate to drop existing tables and create new ones based on entities on application startup
spring.jpa.hibernate.ddl-auto=create-drop

# Change the execution order: first Hibernate creates tables, then data.sql script is executed
spring.jpa.defer-datasource-initialization=true

