spring.application.name=tawerna-mtb-api

# Database connection configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/tawernamtb
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate DDL-Auto configuration (Automatically updates DB schema based on Kotlin entity classes)
spring.jpa.hibernate.ddl-auto=update

# Show raw SQL queries executed by Spring Data JPA in the terminal output
spring.jpa.show-sql=true

# Explicitly define the SQL dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
